# Crime Report Analysis

### 1) Importing Libraries

#### Here imported essential libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

### 2) Data Collection

#### Here reading the csv file for analysis

In [2]:
df = pd.read_csv(r"D:\My Projects\Jupyter Projects\Crime_data_analysis\Crime_Data_from_2020_to_Present.csv")

### 3) Data Understanding / Initial Exploration

In [3]:
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Status,Status Desc,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LOCATION,Cross Street,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,AA,Adult Arrest,510.0,998.0,NaN,NaN,1900 S LONGWOOD AV,NaN,34.0375,-118.3506
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,IC,Invest Cont,330.0,998.0,NaN,NaN,1000 S FLOWER ST,NaN,34.0444,-118.2628
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,IC,Invest Cont,480.0,NaN,NaN,NaN,1400 W 37TH ST,NaN,34.0210,-118.3002
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,IC,Invest Cont,343.0,NaN,NaN,NaN,14000 RIVERSIDE DR,NaN,34.1576,-118.4387
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,IC,Invest Cont,510.0,NaN,NaN,NaN,200 E AVENUE 28,NaN,34.0820,-118.2130

In [4]:
df.shape

(1005199, 28)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1005199 entries, 0 to 1005198
Data columns (total 28 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   DR_NO           1005199 non-null  int64
 1   Date Rptd       1005199 non-null  object
 2   DATE OCC        1005199 non-null  object
 3   TIME OCC        1005199 non-null  int64
 4   AREA            1005199 non-null  int64
 5   AREA NAME       1005199 non-null  object
 6   Rpt Dist No     1005199 non-null  int64
 7   Part 1-2        1005199 non-null  int64
 8   Crm Cd          1005199 non-null  int64
 9   Crm Cd Desc     1005199 non-null  object
 10  Mocodes         853440 non-null   object
 11  Vict Age        1005199 non-null  int64
 12  Vict Sex        860418 non-null   object
 13  Vict Descent    860406 non-null   object
 14  Premis Cd       1005183 non-null  float64
 15  Premis Desc     1004611 non-null  object
 16  Weapon Used Cd  327282 non-null   float64
 17  Weapon Desc     327282 non-null   object
 18  Status          1005198 non-null  object
 19  Status Desc     1005199 non-null  object
 20  Crm Cd 1        1005188 non-null  float64
 21  Crm Cd 2        69159 non-null    float64
 22  Crm Cd 3        2314 non-null     float64
 23  Crm Cd 4        64 non-null       float64
 24  LOCATION        1005199 non-null  object
 25  Cross Street    154244 non-null   object
 26  LAT             1005199 non-null  float64
 27  LON             1005199 non-null  float64
dtypes: float64(8), int64(7), object(13)
memory usage: 214.7+ MB

In [6]:
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1.005199e+06,1.005199e+06,1.005199e+06,1.005199e+06,1.005199e+06,1.005199e+06,1.005199e+06,1.005183e+06,327282.000000,1.005188e+06,69159.000000,2314.000000,64.00000,1.005199e+06,1.005199e+06
mean,2.202278e+08,1.339912e+03,1.069097e+01,1.115556e+03,1.400284e+00,5.001459e+02,2.891254e+01,3.056191e+02,363.954782,4.999065e+02,958.103226,984.015990,991.21875,3.399820e+01,-1.180909e+02
std,1.320295e+07,6.510515e+02,6.110387e+00,6.111736e+02,4.899561e-01,2.052633e+02,2.199378e+01,2.193161e+02,123.734904,2.050638e+02,110.354662,52.350982,27.06985,1.610548e+00,5.581809e+00
min,8.170000e+02,1.000000e+00,1.000000e+00,1.010000e+02,1.000000e+00,1.100000e+02,-4.000000e+00,1.010000e+02,101.000000,1.100000e+02,210.000000,310.000000,821.00000,0.000000e+00,-1.186676e+02
25%,2.106169e+08,9.000000e+02,5.000000e+00,5.870000e+02,1.000000e+00,3.310000e+02,0.000000e+00,1.010000e+02,311.000000,3.310000e+02,998.000000,998.000000,998.00000,3.401470e+01,-1.184305e+02
50%,2.209160e+08,1.420000e+03,1.100000e+01,1.139000e+03,1.000000e+00,4.420000e+02,3.000000e+01,2.030000e+02,400.000000,4.420000e+02,998.000000,998.000000,998.00000,3.405890e+01,-1.183225e+02
75%,2.311105e+08,1.900000e+03,1.600000e+01,1.613000e+03,2.000000e+00,6.260000e+02,4.400000e+01,5.010000e+02,400.000000,6.260000e+02,998.000000,998.000000,998.00000,3.416490e+01,-1.182739e+02
max,2.521041e+08,2.359000e+03,2.100000e+01,2.199000e+03,2.000000e+00,9.560000e+02,1.200000e+02,9.760000e+02,516.000000,9.560000e+02,999.000000,999.000000,999.00000,3.433430e+01,0.000000e+00

In [7]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Weapon Used Cd,Crm Cd 1,Crm Cd 2,Crm Cd 3,Crm Cd 4,LAT,LON
count,1005199.00,1005199.00,1005199.00,1005199.00,1005199.00,1005199.00,1005199.00,1005183.00,327282.00,1005188.00,69159.00,2314.00,64.00,1005199.00,1005199.00
mean,220227767.34,1339.91,10.69,1115.56,1.40,500.15,28.91,305.62,363.95,499.91,958.10,984.02,991.22,34.00,-118.09
std,13202950.48,651.05,6.11,611.17,0.49,205.26,21.99,219.32,123.73,205.06,110.35,52.35,27.07,1.61,5.58
min,817.00,1.00,1.00,101.00,1.00,110.00,-4.00,101.00,101.00,110.00,210.00,310.00,821.00,0.00,-118.67
25%,210616927.50,900.00,5.00,587.00,1.00,331.00,0.00,101.00,311.00,331.00,998.00,998.00,998.00,34.01,-118.43
50%,220916045.00,1420.00,11.00,1139.00,1.00,442.00,30.00,203.00,400.00,442.00,998.00,998.00,998.00,34.06,-118.32
75%,231110518.50,1900.00,16.00,1613.00,2.00,626.00,44.00,501.00,400.00,626.00,998.00,998.00,998.00,34.16,-118.27
max,252104146.00,2359.00,21.00,2199.00,2.00,956.00,120.00,976.00,516.00,956.00,999.00,999.00,999.00,34.33,0.00

### 4) Data Cleaning

In [8]:
cols_nulls = df.isnull().sum()

In [9]:
cols_nulls

DR_NO                   0
Date Rptd               0
DATE OCC                0
TIME OCC                0
AREA                    0
AREA NAME               0
Rpt Dist No             0
Part 1-2                0
Crm Cd                  0
Crm Cd Desc             0
Mocodes            151759
Vict Age                0
Vict Sex           144781
Vict Descent       144793
Premis Cd              16
Premis Desc           588
Weapon Used Cd     677917
Weapon Desc        677917
Status                  1
Status Desc             0
Crm Cd 1               11
Crm Cd 2           936040
Crm Cd 3          1002885
Crm Cd 4          1005135
LOCATION                0
Cross Street       850955
LAT                     0
LON                     0
dtype: int64

In [10]:
columns = df.columns

In [11]:
for i in columns:
    col_nulls2 = df[i].isnull().mean()
    if col_nulls2 > 0.3:
        print(f"{i} has {col_nulls2:.2%} missing values")

Weapon Used Cd has 67.44% missing values
Weapon Desc has 67.44% missing values
Crm Cd 2 has 93.12% missing values
Crm Cd 3 has 99.77% missing values
Crm Cd 4 has 99.99% missing values
Cross Street has 84.66% missing values

In [12]:
for i in columns:
    if(df[i].isnull().mean() > 0.3):
        df.drop(i, axis=1, inplace=True)

In [13]:
df.columns

Index(['DR_NO', 'Date Rptd', 'DATE OCC', 'TIME OCC', 'AREA', 'AREA NAME',
       'Rpt Dist No', 'Part 1-2', 'Crm Cd', 'Crm Cd Desc', 'Mocodes',
       'Vict Age', 'Vict Sex', 'Vict Descent', 'Premis Cd', 'Premis Desc',
       'Status', 'Status Desc', 'Crm Cd 1', 'LOCATION', 'LAT', 'LON'],
      dtype='object')

In [14]:
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Vict Sex,Vict Descent,Premis Cd,Premis Desc,Status,Status Desc,Crm Cd 1,LOCATION,LAT,LON
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,M,O,101.00,STREET,AA,Adult Arrest,510.00,1900 S LONGWOOD AV,34.04,-118.35
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,M,O,128.00,BUS STOP/LAYOVER (ALSO QUERY 124),IC,Invest Cont,330.00,1000 S FLOWER ST,34.04,-118.26
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,X,X,502.00,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,480.00,1400 W 37TH ST,34.02,-118.30
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,M,O,405.00,CLOTHING STORE,IC,Invest Cont,343.00,14000 RIVERSIDE DR,34.16,-118.44
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,NaN,NaN,101.00,STREET,IC,Invest Cont,510.00,200 E AVENUE 28,34.08,-118.21

In [15]:
df.isnull().sum()

DR_NO                0
Date Rptd            0
DATE OCC             0
TIME OCC             0
AREA                 0
AREA NAME            0
Rpt Dist No          0
Part 1-2             0
Crm Cd               0
Crm Cd Desc          0
Mocodes         151759
Vict Age             0
Vict Sex        144781
Vict Descent    144793
Premis Cd           16
Premis Desc        588
Status               1
Status Desc          0
Crm Cd 1            11
LOCATION             0
LAT                  0
LON                  0
dtype: int64

In [16]:
df['time_str'] = df['TIME OCC'].astype(str).str.zfill(4)

df['Time Occured'] = pd.to_datetime(df['time_str'], format='%H%M').dt.strftime('%H:%M')

print(df.head)

<bound method NDFrame.head of              DR_NO               Date Rptd                DATE OCC  TIME OCC  \
0        190326475  03/01/2020 12:00:00 AM  03/01/2020 12:00:00 AM      2130
1        200106753  02/09/2020 12:00:00 AM  02/08/2020 12:00:00 AM      1800
2        200320258  11/11/2020 12:00:00 AM  11/04/2020 12:00:00 AM      1700
3        200907217  05/10/2023 12:00:00 AM  03/10/2020 12:00:00 AM      2037
4        200412582  09/09/2020 12:00:00 AM  09/09/2020 12:00:00 AM       630
...            ...                     ...                     ...       ...
1005194  250304203  02/20/2025 12:00:00 AM  02/13/2025 12:00:00 AM      2100
1005195  250504051  01/14/2025 12:00:00 AM  01/14/2025 12:00:00 AM      1250
1005196  250304284  03/31/2025 12:00:00 AM  03/30/2025 12:00:00 AM      2100
1005197  251604136  02/27/2025 12:00:00 AM  02/27/2025 12:00:00 AM      1550
1005198  251904210  03/25/2025 12:00:00 AM  03/25/2025 12:00:00 AM      1235

         AREA   AREA NAME  Rpt Dist No  Part 1-2  Crm Cd  \
0           7    Wilshire          784         1     510
1           1     Central          182         1     330
2           3   Southwest          356         1     480
3           9    Van Nuys          964         1     343
4           4  Hollenbeck          413         1     510
...       ...         ...          ...       ...     ...
1005194     3   Southwest          325         1     522
1005195     5      Harbor          509         1     210
1005196     3   Southwest          328         1     510
1005197    16    Foothill         1664         1     510
1005198    19     Mission         1944         2     850

                                               Crm Cd Desc  ... Premis Cd  \
0                                         VEHICLE - STOLEN  ...    101.00
1                                    BURGLARY FROM VEHICLE  ...    128.00
2                                            BIKE - STOLEN  ...    502.00
3                 SHOPLIFTING-GRAND THEFT ($950.01 & OVER)  ...    405.00
4                                         VEHICLE - STOLEN  ...    101.00
...                                                    ...  ...       ...
1005194  VEHICLE, STOLEN - OTHER (MOTORIZED SCOOTERS, B...  ...    108.00
1005195                                            ROBBERY  ...    721.00
1005196                                   VEHICLE - STOLEN  ...    101.00
1005197                                   VEHICLE - STOLEN  ...    101.00
1005198                                  INDECENT EXPOSURE  ...    721.00

                                          Premis Desc Status   Status Desc  \
0                                              STREET     AA  Adult Arrest
1                   BUS STOP/LAYOVER (ALSO QUERY 124)     IC   Invest Cont
2        MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)     IC   Invest Cont
3                                      CLOTHING STORE     IC   Invest Cont
4                                              STREET     IC   Invest Cont
...                                               ...    ...           ...
1005194                                   PARKING LOT     IC   Invest Cont
1005195                                   HIGH SCHOOL     IC   Invest Cont
1005196                                        STREET     IC   Invest Cont
1005197                                        STREET     AA  Adult Arrest
1005198                                   HIGH SCHOOL     IC   Invest Cont

         Crm Cd 1                                  LOCATION   LAT     LON  \
0          510.00   1900 S  LONGWOOD                     AV 34.04 -118.35
1          330.00   1000 S  FLOWER                       ST 34.04 -118.26
2          480.00   1400 W  37TH                         ST 34.02 -118.30
3          343.00  14000    RIVERSIDE                    DR 34.16 -118.44
4          510.00                          200 E  AVENUE 28 34.08 -118.21
...           ...                                       ...   ...     ...
1005194    522.00   2600    ELLENDALE                    PL 34.03 -118.29
1005195    210.00  24300    WESTERN                      AV 33.80 -118.31
1005196    510.00    700 W  32ND                         ST 34.02 -118.28
1005197    510.00  11900    SHELDON                      ST 34.24 -118.39
1005198    850.00  11100    OMELVENY                     AV 34.27 -118.44

         time_str Time Occured
0            2130        21:30
1            1800        18:00
2            1700        17:00
3            2037        20:37
4            0630        06:30
...           ...          ...
1005194      2100        21:00
1005195      1250        12:50
1005196      2100        21:00
1005197      1550        15:50
1005198      1235        12:35

[1005199 rows x 24 columns]>

In [17]:
df.head()

,DR_NO,Date Rptd,DATE OCC,TIME OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,...,Premis Cd,Premis Desc,Status,Status Desc,Crm Cd 1,LOCATION,LAT,LON,time_str,Time Occured
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,2130,7,Wilshire,784,1,510,VEHICLE - STOLEN,...,101.00,STREET,AA,Adult Arrest,510.00,1900 S LONGWOOD AV,34.04,-118.35,2130,21:30
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1800,1,Central,182,1,330,BURGLARY FROM VEHICLE,...,128.00,BUS STOP/LAYOVER (ALSO QUERY 124),IC,Invest Cont,330.00,1000 S FLOWER ST,34.04,-118.26,1800,18:00
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,1700,3,Southwest,356,1,480,BIKE - STOLEN,...,502.00,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,480.00,1400 W 37TH ST,34.02,-118.30,1700,17:00
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,2037,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),...,405.00,CLOTHING STORE,IC,Invest Cont,343.00,14000 RIVERSIDE DR,34.16,-118.44,2037,20:37
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,630,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,...,101.00,STREET,IC,Invest Cont,510.00,200 E AVENUE 28,34.08,-118.21,0630,06:30

In [18]:
pd.set_option('display.float_format', lambda x: '%.2f' % x)
df.describe()

,DR_NO,TIME OCC,AREA,Rpt Dist No,Part 1-2,Crm Cd,Vict Age,Premis Cd,Crm Cd 1,LAT,LON
count,1005199.00,1005199.00,1005199.00,1005199.00,1005199.00,1005199.00,1005199.00,1005183.00,1005188.00,1005199.00,1005199.00
mean,220227767.34,1339.91,10.69,1115.56,1.40,500.15,28.91,305.62,499.91,34.00,-118.09
std,13202950.48,651.05,6.11,611.17,0.49,205.26,21.99,219.32,205.06,1.61,5.58
min,817.00,1.00,1.00,101.00,1.00,110.00,-4.00,101.00,110.00,0.00,-118.67
25%,210616927.50,900.00,5.00,587.00,1.00,331.00,0.00,101.00,331.00,34.01,-118.43
50%,220916045.00,1420.00,11.00,1139.00,1.00,442.00,30.00,203.00,442.00,34.06,-118.32
75%,231110518.50,1900.00,16.00,1613.00,2.00,626.00,44.00,501.00,626.00,34.16,-118.27
max,252104146.00,2359.00,21.00,2199.00,2.00,956.00,120.00,976.00,956.00,34.33,0.00

In [19]:
# Invalid time check
invalid_times = []

for time in df['TIME OCC']:
    if pd.isnull(time):
        continue
    hour = int(time) // 100
    minute = int(time) % 100
    if hour > 23 or minute > 59:
        invalid_times.append(time)

print("Invalid TIME OCC values found:", len(invalid_times))
print("Examples:", invalid_times[:10])

#doubt

Invalid TIME OCC values found: 0
Examples: []

In [20]:
count = 0
for i in df['Vict Age']:
    if i < 0:
        count += 1
print(count)

136

In [21]:
invalid_ages = df[(df['Vict Age'] < 0)]
print(invalid_ages['Vict Age'].value_counts())

Vict Age
-1    99
-2    28
-3     6
-4     3
Name: count, dtype: int64

In [22]:
df['Vict Age'].value_counts()

Vict Age
 0      269375
 30      22290
 35      21836
 31      21420
 29      21345
         ...
 98         71
-2          28
-3           6
-4           3
 120         1
Name: count, Length: 104, dtype: int64

In [23]:
median_age = df['Vict Age'].median()
df.loc[(df['Vict Age'] < 0), 'Vict Age'] = median_age
print(df['Vict Age'].value_counts())

Vict Age
0      269375
30      22426
35      21836
31      21420
29      21345
        ...
95        100
96         95
97         72
98         71
120         1
Name: count, Length: 100, dtype: int64

In [24]:
count = 0
for i in df['Vict Age']:
    if i < 0:
        count += 1
print(count)

0

In [25]:
df.duplicated().sum()

0

#### changed the format of Time so there were two extra similar time columns so we dropped

In [26]:
df.drop(['TIME OCC','time_str'],axis = 1, inplace=True)

In [27]:
df.head()

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Vict Descent,Premis Cd,Premis Desc,Status,Status Desc,Crm Cd 1,LOCATION,LAT,LON,Time Occured
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,7,Wilshire,784,1,510,VEHICLE - STOLEN,NaN,...,O,101.00,STREET,AA,Adult Arrest,510.00,1900 S LONGWOOD AV,34.04,-118.35,21:30
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1,Central,182,1,330,BURGLARY FROM VEHICLE,1822 1402 0344,...,O,128.00,BUS STOP/LAYOVER (ALSO QUERY 124),IC,Invest Cont,330.00,1000 S FLOWER ST,34.04,-118.26,18:00
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,3,Southwest,356,1,480,BIKE - STOLEN,0344 1251,...,X,502.00,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,480.00,1400 W 37TH ST,34.02,-118.30,17:00
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),0325 1501,...,O,405.00,CLOTHING STORE,IC,Invest Cont,343.00,14000 RIVERSIDE DR,34.16,-118.44,20:37
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,NaN,...,NaN,101.00,STREET,IC,Invest Cont,510.00,200 E AVENUE 28,34.08,-118.21,06:30

In [28]:
df['Vict Sex'].unique()

array(['M', 'X', nan, 'F', 'H', '-'], dtype=object)

In [29]:
df['Vict Sex'].value_counts()

Vict Sex
M    403917
F    358600
X     97786
H       114
-         1
Name: count, dtype: int64

In [30]:
df['Vict Sex'] = df['Vict Sex'].replace('-', np.nan)

In [31]:
df['Vict Sex'].value_counts()

Vict Sex
M    403917
F    358600
X     97786
H       114
Name: count, dtype: int64

In [32]:
df['Vict Sex'] = df['Vict Sex'].fillna('Unknown')

In [33]:
df['Vict Sex'].value_counts()

Vict Sex
M          403917
F          358600
Unknown    144782
X           97786
H             114
Name: count, dtype: int64

In [34]:
df.isnull().sum()

DR_NO                0
Date Rptd            0
DATE OCC             0
AREA                 0
AREA NAME            0
Rpt Dist No          0
Part 1-2             0
Crm Cd               0
Crm Cd Desc          0
Mocodes         151759
Vict Age             0
Vict Sex             0
Vict Descent    144793
Premis Cd           16
Premis Desc        588
Status               1
Status Desc          0
Crm Cd 1            11
LOCATION             0
LAT                  0
LON                  0
Time Occured         0
dtype: int64

In [35]:
df['Vict Sex'] = df['Vict Sex'].replace(['X','H'], 'Others')

In [36]:
df['Vict Sex'].value_counts()

Vict Sex
M          403917
F          358600
Unknown    144782
Others      97900
Name: count, dtype: int64

In [37]:
df['Vict Descent'].value_counts()

Vict Descent
H    296440
W    201451
B    135823
X    106699
O     78009
A     21340
K      5991
F      4838
C      4631
J      1586
V      1195
I      1015
Z       577
P       288
U       221
D        91
L        77
G        74
S        58
-         2
Name: count, dtype: int64

In [38]:
df['Vict Descent'] = df['Vict Descent'].replace('-', 'X')

In [39]:
df['Vict Descent'].value_counts()

Vict Descent
H    296440
W    201451
B    135823
X    106701
O     78009
A     21340
K      5991
F      4838
C      4631
J      1586
V      1195
I      1015
Z       577
P       288
U       221
D        91
L        77
G        74
S        58
Name: count, dtype: int64

In [40]:
df['Vict Descent'] = df['Vict Descent'].replace(np.nan, 'X')

In [41]:
df['Vict Descent'].value_counts()

Vict Descent
H    296440
X    251494
W    201451
B    135823
O     78009
A     21340
K      5991
F      4838
C      4631
J      1586
V      1195
I      1015
Z       577
P       288
U       221
D        91
L        77
G        74
S        58
Name: count, dtype: int64

In [42]:
df.isnull().sum()

DR_NO                0
Date Rptd            0
DATE OCC             0
AREA                 0
AREA NAME            0
Rpt Dist No          0
Part 1-2             0
Crm Cd               0
Crm Cd Desc          0
Mocodes         151759
Vict Age             0
Vict Sex             0
Vict Descent         0
Premis Cd           16
Premis Desc        588
Status               1
Status Desc          0
Crm Cd 1            11
LOCATION             0
LAT                  0
LON                  0
Time Occured         0
dtype: int64

In [43]:
df['Mocodes'] = df['Mocodes'].replace(np.nan, 'Unknown')

In [44]:
df['Mocodes'].value_counts()

Mocodes
Unknown                               151759
0344                                   42201
0329                                   21631
1822 0344                              14250
0325                                   10278
                                       ...
1822 0342 0334 0302 0432 1309 2035         1
0913 1813 1601 0419 0429 2000 1402         1
1402 0913 0329 0907                        1
0421 1202 0561                             1
0529 2024 1815 0913                        1
Name: count, Length: 310959, dtype: int64

In [45]:
df.isnull().sum()

DR_NO             0
Date Rptd         0
DATE OCC          0
AREA              0
AREA NAME         0
Rpt Dist No       0
Part 1-2          0
Crm Cd            0
Crm Cd Desc       0
Mocodes           0
Vict Age          0
Vict Sex          0
Vict Descent      0
Premis Cd        16
Premis Desc     588
Status            1
Status Desc       0
Crm Cd 1         11
LOCATION          0
LAT               0
LON               0
Time Occured      0
dtype: int64

In [46]:
df['Premis Cd'].unique()

array([101., 128., 502., 405., 221., 201., 203., 108., 103., 301., 247.,
       501., 507., 210., 102., 510., 402., 725., 104., 401., 121., 122.,
       707., 123., 220., 119., 403., 801., 906., 710., 231., 124., 726.,
       517., 708., 235., 242., 903., 702., 406., 232., 503., 253., 504.,
       116., 949., 720., 735., 252., 750., 721., 118., 254., 218., 505.,
       156., 109., 518., 222., 208., 704., 834., 945., 214., 729., 713.,
       753., 243., 249., 514., 251., 835., 508., 114., 418., 701., 404.,
       511., 158., 904., 415., 516., 722., 755., 229., 152., 717., 145.,
       719., 202., 217., 106., 408., 946., 727., 409., 142., 417., 709.,
       966., 732., 515., 730., 718., 802., 506., 211., 407., 741., 935.,
       738., 413., 138., 120., 744., 416., 206., 244., 900., 146., 248.,
       754., 916., 219., 901., 605., 519., 411., 971., 728., 509., 606.,
       110., 207., 410., 602., 230., 902., 705., 140., 716., 157., 141.,
       948., 723., 603., 213., 303., 736., 908., 117., 154., 205., 712.,
       239., 751., 512., 907., 953., 412., 151., 236., 127., 212., 911.,
       115., 706., 733., 255., 105., 897., 757., 940., 703., 954., 144.,
       752., 238., 302., 910., 742., 148., 919., 237., 934., 111., 149.,
       876., 896., 204., 233., 234., 944., 895., 877., 147., 809., 947.,
       950., 209., 107., 933., 932., 607., 139., 943., 739., 931., 909.,
       256., 216., 112., 970., 974., 804., 724., 915., 962., 937., 228.,
       871., 941., 872., 740., 135., 918., 811., 608., 250., 968., 513.,
       963., 952., 414., 601., 893., 875., 227., 215., 917., 874., 969.,
        nan, 225., 936., 890., 746., 714., 892., 967., 961., 150., 246.,
       125., 810., 891., 223., 113., 898., 224., 715., 245., 604., 155.,
       748., 873., 965., 964., 743., 745., 136., 942., 870., 143., 882.,
       868., 913., 921., 241., 885., 922., 912., 905., 956., 920., 957.,
       951., 737., 758., 880., 884., 129., 756., 958., 711., 304., 869.,
       878., 883., 731., 879., 137., 803., 305., 889., 240., 805., 126.,
       734., 894., 836., 972., 973., 976., 975.])

In [47]:
mode_premis_cd = df['Premis Cd'].mode()

In [48]:
mode_premis_cd

0   101.00
Name: Premis Cd, dtype: float64

In [49]:
df['Premis Cd']=df['Premis Cd'].fillna(df['Premis Cd'].mode()[0])

In [50]:
df['Premis Cd'].unique()

array([101., 128., 502., 405., 221., 201., 203., 108., 103., 301., 247.,
       501., 507., 210., 102., 510., 402., 725., 104., 401., 121., 122.,
       707., 123., 220., 119., 403., 801., 906., 710., 231., 124., 726.,
       517., 708., 235., 242., 903., 702., 406., 232., 503., 253., 504.,
       116., 949., 720., 735., 252., 750., 721., 118., 254., 218., 505.,
       156., 109., 518., 222., 208., 704., 834., 945., 214., 729., 713.,
       753., 243., 249., 514., 251., 835., 508., 114., 418., 701., 404.,
       511., 158., 904., 415., 516., 722., 755., 229., 152., 717., 145.,
       719., 202., 217., 106., 408., 946., 727., 409., 142., 417., 709.,
       966., 732., 515., 730., 718., 802., 506., 211., 407., 741., 935.,
       738., 413., 138., 120., 744., 416., 206., 244., 900., 146., 248.,
       754., 916., 219., 901., 605., 519., 411., 971., 728., 509., 606.,
       110., 207., 410., 602., 230., 902., 705., 140., 716., 157., 141.,
       948., 723., 603., 213., 303., 736., 908., 117., 154., 205., 712.,
       239., 751., 512., 907., 953., 412., 151., 236., 127., 212., 911.,
       115., 706., 733., 255., 105., 897., 757., 940., 703., 954., 144.,
       752., 238., 302., 910., 742., 148., 919., 237., 934., 111., 149.,
       876., 896., 204., 233., 234., 944., 895., 877., 147., 809., 947.,
       950., 209., 107., 933., 932., 607., 139., 943., 739., 931., 909.,
       256., 216., 112., 970., 974., 804., 724., 915., 962., 937., 228.,
       871., 941., 872., 740., 135., 918., 811., 608., 250., 968., 513.,
       963., 952., 414., 601., 893., 875., 227., 215., 917., 874., 969.,
       225., 936., 890., 746., 714., 892., 967., 961., 150., 246., 125.,
       810., 891., 223., 113., 898., 224., 715., 245., 604., 155., 748.,
       873., 965., 964., 743., 745., 136., 942., 870., 143., 882., 868.,
       913., 921., 241., 885., 922., 912., 905., 956., 920., 957., 951.,
       737., 758., 880., 884., 129., 756., 958., 711., 304., 869., 878.,
       883., 731., 879., 137., 803., 305., 889., 240., 805., 126., 734.,
       894., 836., 972., 973., 976., 975.])

In [51]:
df.isnull().sum()

DR_NO             0
Date Rptd         0
DATE OCC          0
AREA              0
AREA NAME         0
Rpt Dist No       0
Part 1-2          0
Crm Cd            0
Crm Cd Desc       0
Mocodes           0
Vict Age          0
Vict Sex          0
Vict Descent      0
Premis Cd         0
Premis Desc     588
Status            1
Status Desc       0
Crm Cd 1         11
LOCATION          0
LAT               0
LON               0
Time Occured      0
dtype: int64

In [52]:
df['Premis Desc'].unique()

array(['STREET', 'BUS STOP/LAYOVER (ALSO QUERY 124)',
       'MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)', 'CLOTHING STORE',
       'PUBLIC STORAGE', 'JEWELRY STORE', 'OTHER BUSINESS', 'PARKING LOT',
       'ALLEY', 'GAS STATION', 'CAR WASH', 'SINGLE FAMILY DWELLING',
       'CONDOMINIUM/TOWNHOUSE', 'RESTAURANT/FAST FOOD', 'SIDEWALK',
       'NURSING/CONVALESCENT/RETIREMENT HOME', 'MARKET',
       'GOVERNMENT FACILITY (FEDERAL,STATE, COUNTY & CITY)', 'DRIVEWAY',
       'MINI-MART', 'YARD (RESIDENTIAL/BUSINESS)',
       'VEHICLE, PASSENGER/TRUCK', 'GARAGE/CARPORT',
       'PARKING UNDERGROUND/BUILDING', 'NAIL SALON', 'PORCH, RESIDENTIAL',
       'DRUG STORE', 'MTA BUS', 'MTA - RED LINE - VERMONT/BEVERLY',
       'OTHER PREMISE', 'DAY CARE/CHILDREN*', 'BUS STOP',
       'POLICE FACILITY', 'MISSIONS/SHELTERS',
       'CHURCH/CHAPEL (CHANGED 03-03 FROM CHURCH/TEMPLE)',
       'PHARMACY INSIDE STORE OR SUPERMARKET*',
       'DISCOUNT STORE (99 CENT,DOLLAR,ETC.',
       'MTA - RED LINE - 7TH AND METRO CENTER', 'OFFICE BUILDING/OFFICE',
       'OTHER STORE',
       'DELIVERY SERVICE (FED EX, UPS, COURIERS,COURIER SERVICE)*',
       'HOTEL', 'MORTUARY', 'OTHER RESIDENCE', 'OTHER/OUTSIDE',
       'MTA - EXPO LINE - EXPO/LA BREA', 'JUNIOR HIGH SCHOOL',
       'NIGHT CLUB (OPEN EVENINGS ONLY)',
       "COFFEE SHOP (STARBUCKS, COFFEE BEAN, PEET'S, ETC.)", 'CYBERSPACE',
       'HIGH SCHOOL', 'CONSTRUCTION SITE',
       'STUDIO (FILM/PHOTOGRAPHIC/MUSIC)', 'BEAUTY/BARBER SHOP', 'MOTEL',
       'VALET', 'PARK/PLAYGROUND', 'TRANSITIONAL HOUSING/HALFWAY HOUSE',
       'LAUNDROMAT', 'AUTO SALES LOT', 'ELEMENTARY SCHOOL',
       'LA UNION STATION (NOT LINE SPECIFIC)',
       'MTA - EXPO LINE - EXPO/VERMONT',
       'BUS DEPOT/TERMINAL, OTHER THAN MTA', 'SPECIALTY SCHOOL/OTHER',
       'CONVENTION CENTER', 'DETENTION/JAIL FACILITY',
       "DIY CENTER (LOWE'S,HOME DEPOT,OSH,CONTRACTORS WAREHOUSE)",
       'NURSERY/FLOWER SHOP', 'GROUP HOME', 'RECYCLING CENTER',
       '7TH AND METRO CENTER (NOT LINE SPECIFIC)',
       'FRAT HOUSE/SORORITY/DORMITORY', 'TAXI', nan, 'HOSPITAL',
       'DEPARTMENT STORE', 'PROJECT/TENEMENT/PUBLIC HOUSING',
       'TRANSIENT ENCAMPMENT', 'MTA - RED LINE - WESTLAKE/MACARTHUR PARK',
       'THE GROVE', "SINGLE RESIDENCE OCCUPANCY (SRO'S) LOCATIONS",
       'COLLEGE/JUNIOR COLLEGE/UNIVERSITY',
       'VETERINARIAN/ANIMAL HOSPITAL', 'CHECK CASHING*',
       'UNDERPASS/BRIDGE*', 'HEALTH SPA/GYM', 'MAIL BOX',
       'MEDICAL/DENTAL OFFICES', 'LIQUOR STORE', 'AUTO REPAIR SHOP',
       'TUNNEL', 'AUTO SUPPLY STORE*', 'MTA - EXPO LINE - EXPO/WESTERN',
       'SHOPPING MALL (COMMON AREA)', 'BEAUTY SUPPLY STORE',
       'DRIVE THRU*', 'THE BEVERLY CONNECTION',
       'PUBLIC RESTROOM(INDOORS-INSIDE)',
       'MTA - GOLD LINE - UNION STATION', 'POST OFFICE',
       'APARTMENT/CONDO COMMON LAUNDRY ROOM', 'SYNAGOGUE/TEMPLE',
       'MASSAGE PARLOR', 'MUNICIPAL BUS LINE INCLUDES LADOT/DASH',
       'ABANDONED BUILDING ABANDONED HOUSE', 'PAWN SHOP',
       'HARDWARE/BUILDING SUPPLY', 'STAPLES CENTER *',
       'MTA - BLUE LINE - WASHINGTON', 'LIBRARY', 'FURNITURE STORE',
       'STAIRWELL*', 'STORAGE SHED', 'HIGH-RISE BUILDING',
       'THE BEVERLY CENTER', 'TV/RADIO/APPLIANCE', 'TOBACCO SHOP',
       'MTA - RED LINE - UNION STATION', 'PATIO*', 'CELL PHONE STORE',
       'MUSEUM', 'MTA - PURPLE LINE - CIVIC CENTER/GRAND PARK',
       'CLEANER/LAUNDROMAT', 'MTA - RED LINE - CIVIC CENTER/GRAND PARK',
       'AUTOMATED TELLER MACHINE (ATM)', 'SHORT-TERM VACATION RENTAL',
       'PET STORE', 'MTA - GOLD LINE - HIGHLAND PARK', 'ELEVATOR',
       "MOBILE HOME/TRAILERS/CONSTRUCTION TRAILERS/RV'S/MOTORHOME",
       'DRIVE THRU BANKING (WINDOW)*', 'FREEWAY',
       'BAR/COCKTAIL/NIGHTCLUB', 'MEMBERSHIP STORE (COSTCO,SAMS CLUB)*',
       'BANK', 'DAY CARE/ADULTS*', 'MTA - RED LINE - PERSHING SQUARE',
       'SLIPS/DOCK/MARINA/BOAT', 'BALCONY*', 'THEATRE/MOVIE',
       "VEHICLE STORAGE LOT (CARS, TRUCKS, RV'S, BOATS, TRAILERS, ETC.)",
       'CEMETARY*', 'MTA - EXPO LINE - FARMDALE',
       'PRIVATE SCHOOL/PRESCHOOL', 'CREDIT UNION', 'WAREHOUSE',
       'OIL REFINERY', 'SKATEBOARD FACILITY/SKATEBOARD PARK*',
       'MTA - RED LINE - VERMONT/SUNSET', 'BEACH', 'TRAIN TRACKS',
       'GUN/SPORTING GOODS', 'COLISEUM',
       'MEDICAL MARIJUANA FACILITIES/BUSINESSES', 'WEBSITE',
       'FOSTER HOME BOYS OR GIRLS*',
       'MTA - RED LINE - VERMONT/SANTA MONICA',
       'MTA - EXPO LINE - EXPO/SEPULVEDA',
       'ELECTRONICS STORE (IE:RADIO SHACK, ETC.)', 'TOW YARD*',
       'VISION CARE FACILITY*', 'TRASH CAN/TRASH DUMPSTER',
       'TRANSPORTATION FACILITY (AIRPORT)',
       'MTA - RED LINE - HOLLYWOOD/HIGHLAND', 'AIRCRAFT',
       "SEX ORIENTED/BOOK STORE/STRIP CLUB/GENTLEMAN'S CLUB",
       'BAR/SPORTS BAR (OPEN DAY & NIGHT)',
       'AUTO DEALERSHIP (CHEVY, FORD, BMW, MERCEDES, ETC.)',
       'PEDESTRIAN OVERCROSSING',
       'MTA - SILVER LINE - HARBOR GATEWAY TRANSIT CTR',
       'BASKETBALL COURTS', 'MTA - EXPO LINE - 7TH AND METRO CENTER',
       'ENTERTAINMENT/COMEDY CLUB (OTHER)',
       'MTA - EXPO LINE - EXPO/BUNDY', 'GOLF COURSE*', 'FIRE STATION',
       'TELECOMMUNICATION FACILITY/LOCATION', 'FACTORY',
       'MTA - RED LINE - HOLLYWOOD/VINE', 'SPORTS VENUE, OTHER',
       'PUBLIC RESTROOM/OUTSIDE*',
       'MTA - PURPLE LINE - WESTLAKE/MACARTHUR PARK', 'HOSPICE',
       'MTA - BLUE LINE - SAN PEDRO', 'BUS-CHARTER/PRIVATE', 'RIVER BED*',
       'MTA - ORANGE LINE - RESEDA', 'MTA - SILVER LINE - ROSECRANS',
       'MANUFACTURING COMPANY', 'TATTOO PARLOR*',
       'OPTICAL OFFICE INSIDE STORE OR SUPERMARKET*',
       'MTA - EXPO LINE - EXPO PARK/USC',
       'MTA - SILVER LINE - HARBOR FWY', 'MTA - ORANGE LINE - TAMPA',
       'POOL-PUBLIC/OUTDOOR OR INDOOR*', 'METROLINK TRAIN',
       'MTA - EXPO LINE - EXPO/CRENSHAW',
       'MTA - EXPO LINE - LA CIENEGA/JEFFERSON', 'EQUIPMENT RENTAL',
       'VACANT LOT', 'MTA - BLUE LINE - GRAND/LATTC',
       'MTA - BLUE LINE - PICO', 'BANKING INSIDE MARKET-STORE *',
       'AMUSEMENT PARK*', 'MTA - EXPO LINE - JEFFERSON/USC',
       'SPORTS ARENA', 'MTA - BLUE LINE - 7TH AND METRO CENTER',
       'MTA - RED LINE - HOLLYWOOD/WESTERN', 'SWAP MEET',
       'BUS, SCHOOL, CHURCH', 'MTA - GOLD LINE - SOUTHWEST MUSEUM',
       'GREYHOUND OR INTERSTATE BUS',
       'TRADE SCHOOL (MEDICAL-TECHNICAL-BUSINESS)*',
       'MTA - PURPLE LINE - UNION STATION', 'MTA - GOLD LINE - SOTO',
       'MTA - BLUE LINE - 103RD/WATTS TOWERS', 'BOWLING ALLEY*',
       'MTA - ORANGE LINE - WOODMAN', 'MTA - EXPO LINE - PICO',
       'MTA - ORANGE LINE - VAN NUYS', 'OTHER PLACE OF WORSHIP',
       'MTA PROPERTY OR PARKING LOT',
       'MTA - PURPLE LINE - 7TH AND METRO CENTER',
       'OTHER RR TRAIN (UNION PAC, SANTE FE ETC',
       'BANK DROP BOX/MONEY DROP-OUTSIDE OF BANK*',
       'COMPUTER SERVICES/REPAIRS/SALES',
       'MTA - GOLD LINE - LINCOLN/CYPRESS', 'ABATEMENT LOCATION',
       'MTA - GOLD LINE - MARIACHI PLAZA',
       'MTA - EXPO LINE - WESTWOOD/RANCHO PARK', 'BOOK STORE',
       'SAVINGS & LOAN', 'MTA - SILVER LINE - SLAUSON',
       'MTA - ORANGE LINE - BALBOA', 'ABORTION CLINIC/ABORTION FACILITY*',
       'TRAIN DEPOT/TERMINAL, OTHER THAN MTA',
       'MTA - PURPLE LINE - PERSHING SQUARE',
       'MTA - ORANGE LINE - WOODLEY', 'MTA - GOLD LINE - HERITAGE SQ',
       'RECORD-CD MUSIC/COMPUTER GAME STORE', 'MTA - BLUE LINE - VERNON',
       'MTA - SILVER LINE - UNION STATION', 'SEWAGE FACILITY/PIPE',
       'DODGER STADIUM', 'MTA - SILVER LINE - 37TH ST/USC',
       'MTA - GOLD LINE - CHINATOWN', 'MTA - GOLD LINE - INDIANA',
       'TOOL SHED*', 'METHADONE CLINIC', 'PAY PHONE', 'AMTRAK TRAIN',
       'MTA - SILVER LINE - DOWNTOWN STREET STOPS', 'VIDEO RENTAL STORE',
       'TRUCK, COMMERICAL', 'MTA - SILVER LINE - PACIFIC COAST HWY',
       'SURPLUS SURVIVAL STORE', 'HORSE RACING/SANTA ANITA PARK*',
       'CATERING/ICE CREAM TRUCK', 'FINANCE COMPANY', 'DAM/RESERVOIR',
       'CULTURAL SIGNIFICANCE/MONUMENT', 'MTA - ORANGE LINE - SEPULVEDA',
       'MTA - GOLD LINE - LITTLE TOKYO/ARTS DISTRICT',
       'MTA - GOLD LINE - PICO/ALISO', 'MASS GATHERING LOCATION',
       'WATER FACILITY', 'OTHER INTERSTATE, CHARTER BUS',
       'MTA - EXPO LINE - LATTC/ORTHO INSTITUTE',
       'MTA - ORANGE LINE - VALLEY COLLEGE', 'ESCALATOR*',
       'MTA - ORANGE LINE - SHERMAN WAY',
       'MTA - ORANGE LINE - NORTH HOLLYWOOD',
       'MTA - RED LINE - NORTH HOLLYWOOD',
       'MTA - PURPLE LINE - WILSHIRE/NORMANDIE', 'ENERGY PLANT/FACILITY',
       'MTA - ORANGE LINE - CHATSWORTH',
       'MTA - PURPLE LINE - WILSHIRE/WESTERN',
       'MTA - RED LINE - UNIVERSAL CITY/STUDIO CITY',
       'MTA - RED LINE - WILSHIRE/VERMONT', 'MTA - GREEN LINE - AVALON',
       'MTA - PURPLE LINE - WILSHIRE/VERMONT',
       'MTA - GREEN LINE - HARBOR FWY', 'MTA - EXPO LINE - PALMS',
       'SKATING RINK*', 'HANDBALL COURTS', 'MTA - ORANGE LINE - CANOGA',
       'MTA - ORANGE LINE - NORDHOFF', 'TERMINAL, OTHER THAN MTA',
       'MUSCLE BEACH', 'MTA - GREEN LINE - AVIATION/LAX',
       'ARCADE,GAME ROOM/VIDEO GAMES (EXAMPLE CHUCKIE CHEESE)*',
       'GARMENT MANUFACTURER', 'MTA - ORANGE LINE - LAUREL CANYON',
       'MTA - ORANGE LINE - PIERCE COLLEGE', 'MTA - ORANGE LINE - ROSCOE',
       'MOSQUE*', 'MTA - ORANGE LINE - DE SOTO',
       'TRAM/STREETCAR(BOXLIKE WAG ON RAILS)*',
       'RETIRED (DUPLICATE) DO NOT USE THIS CODE',
       'CHEMICAL STORAGE/MANUFACTURING PLANT',
       'MTA - SILVER LINE - LAC/USC MEDICAL CENTER',
       'DEPT OF DEFENSE FACILITY',
       'TRAIN, OTHER THAN MTA (ALSO QUERY 809/810/811)',
       'HOCKEY RINK/ICE HOCKEY', 'MTA - SILVER LINE - MANCHESTER',
       'HARBOR FRWY STATION (NOT LINE SPECIFIC)'], dtype=object)

In [53]:
df['Premis Desc'] = df['Premis Desc'].replace(np.nan, 'Unknown')

In [54]:
df.isnull().sum()

DR_NO            0
Date Rptd        0
DATE OCC         0
AREA             0
AREA NAME        0
Rpt Dist No      0
Part 1-2         0
Crm Cd           0
Crm Cd Desc      0
Mocodes          0
Vict Age         0
Vict Sex         0
Vict Descent     0
Premis Cd        0
Premis Desc      0
Status           1
Status Desc      0
Crm Cd 1        11
LOCATION         0
LAT              0
LON              0
Time Occured     0
dtype: int64

In [55]:
df['Status'].unique()

array(['AA', 'IC', 'AO', 'JA', 'JO', 'CC', nan], dtype=object)

In [56]:
df['Status'] = df['Status'].replace(np.nan, 'Unknown')

In [57]:
df.isnull().sum()

DR_NO            0
Date Rptd        0
DATE OCC         0
AREA             0
AREA NAME        0
Rpt Dist No      0
Part 1-2         0
Crm Cd           0
Crm Cd Desc      0
Mocodes          0
Vict Age         0
Vict Sex         0
Vict Descent     0
Premis Cd        0
Premis Desc      0
Status           0
Status Desc      0
Crm Cd 1        11
LOCATION         0
LAT              0
LON              0
Time Occured     0
dtype: int64

In [58]:
df['Crm Cd 1']=df['Crm Cd 1'].fillna(df['Crm Cd 1'].mode()[0])

In [59]:
df['Crm Cd 1'].unique()

array([510., 330., 480., 343., 648., 310., 805., 806., 946., 745., 626.,
       210., 341., 230., 354., 624., 442., 662., 900., 901., 440., 740.,
       121., 331., 888., 520., 437., 668., 410., 956., 930., 845., 661.,
       420., 237., 761., 320., 753., 623., 522., 820., 850., 450., 627.,
       625., 886., 236., 755., 890., 903., 220., 231., 649., 664., 815.,
       251., 922., 951., 920., 250., 350., 235., 940., 470., 810., 812.,
       860., 822., 813., 651., 122., 434., 647., 762., 932., 910., 110.,
       763., 441., 821., 902., 814., 756., 433., 421., 352., 443., 660.,
       666., 950., 943., 439., 933., 345., 928., 351., 670., 652., 949.,
       760., 622., 446., 113., 438., 471., 451., 436., 521., 653., 654.,
       474., 921., 485., 954., 942., 487., 944., 347., 865., 870., 473.,
       880., 475., 444., 435., 906., 931., 349., 353., 430., 452., 924.,
       840., 948., 884., 904., 830., 432., 882., 445., 926., 453.])

In [60]:
df.isnull().sum()

DR_NO           0
Date Rptd       0
DATE OCC        0
AREA            0
AREA NAME       0
Rpt Dist No     0
Part 1-2        0
Crm Cd          0
Crm Cd Desc     0
Mocodes         0
Vict Age        0
Vict Sex        0
Vict Descent    0
Premis Cd       0
Premis Desc     0
Status          0
Status Desc     0
Crm Cd 1        0
LOCATION        0
LAT             0
LON             0
Time Occured    0
dtype: int64

In [61]:
df.head()

,DR_NO,Date Rptd,DATE OCC,AREA,AREA NAME,Rpt Dist No,Part 1-2,Crm Cd,Crm Cd Desc,Mocodes,...,Vict Descent,Premis Cd,Premis Desc,Status,Status Desc,Crm Cd 1,LOCATION,LAT,LON,Time Occured
0,190326475,03/01/2020 12:00:00 AM,03/01/2020 12:00:00 AM,7,Wilshire,784,1,510,VEHICLE - STOLEN,Unknown,...,O,101.00,STREET,AA,Adult Arrest,510.00,1900 S LONGWOOD AV,34.04,-118.35,21:30
1,200106753,02/09/2020 12:00:00 AM,02/08/2020 12:00:00 AM,1,Central,182,1,330,BURGLARY FROM VEHICLE,1822 1402 0344,...,O,128.00,BUS STOP/LAYOVER (ALSO QUERY 124),IC,Invest Cont,330.00,1000 S FLOWER ST,34.04,-118.26,18:00
2,200320258,11/11/2020 12:00:00 AM,11/04/2020 12:00:00 AM,3,Southwest,356,1,480,BIKE - STOLEN,0344 1251,...,X,502.00,"MULTI-UNIT DWELLING (APARTMENT, DUPLEX, ETC)",IC,Invest Cont,480.00,1400 W 37TH ST,34.02,-118.30,17:00
3,200907217,05/10/2023 12:00:00 AM,03/10/2020 12:00:00 AM,9,Van Nuys,964,1,343,SHOPLIFTING-GRAND THEFT ($950.01 & OVER),0325 1501,...,O,405.00,CLOTHING STORE,IC,Invest Cont,343.00,14000 RIVERSIDE DR,34.16,-118.44,20:37
4,200412582,09/09/2020 12:00:00 AM,09/09/2020 12:00:00 AM,4,Hollenbeck,413,1,510,VEHICLE - STOLEN,Unknown,...,X,101.00,STREET,IC,Invest Cont,510.00,200 E AVENUE 28,34.08,-118.21,06:30

In [62]:
df.shape

(1005199, 22)

In [63]:
df.to_csv(r'D:\My Projects\Jupyter Projects\Crime_data_analysis\cleaned_crime_dataset.csv', index=False)